POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Тестовый пользователь1",
  "about": "Информация о себе",
  "avatar": "https://trueposters.ru/pictures/product/big/8210_big.jpg"
}

###

POST  http://localhost:3000/cards
Content-Type: application/json

{
  "name": "Тестовая карточка55",
  "link": "https://trueposters.ru/pictures/product/big/8210_big.jpg"
}

###

GET http://localhost:3000/cards

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/62def0a742948ec662500c51

###

PATCH  http://localhost:3000/users/me
Content-Type: application/json

{
  "name": "Тестовый пользователь3",
  "about": "Информация о себе"
}

###

PATCH  http://localhost:3000/users/me/avatar
Content-Type: application/json

{
  "avatar": "https://yandex.ru/images/search?utm_source=main_stripe_big&text=Северный%20Олень&nl=1&source=morda"
}

###

DELETE  http://localhost:3000/cards/62e19c1256b7f4eba47faf37

###

DELETE  http://localhost:3000/cards/62e19d3743cb848c2b96aba7/likes

###

PUT http://localhost:3000/cards/62e19d3743cb848c2b96aba7/likes

###
POST http://api.mesto.nn.nomoredomains.sbs/signin
Content-Type: application/json

{
  "email": "12345678@mail.ru",
  "password": "12345678"
}

###
GET  http://mesto.nn.nomoredomains.sbs/api/signup

{

}



